
(function(){
var API="http://localhost:3000/api",T=0,D={s:[],c:[],k:[],p:[]},cb=null;
function E(s){if(!s)return"";s=String(s);return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function F(d){if(!d)return"-";var t=new Date(d);return t.getFullYear()+"-"+String(t.getMonth()+1).padStart(2,"0")+"-"+String(t.getDate()).padStart(2,"0")}
function GS(id){return D.s.find(function(s){return s.id===id||s.phone===id})||{name:"?",phone:"?"}}
function TX(m){var e=document.getElementById("toast");e.textContent=m;e.classList.add("show");setTimeout(function(){e.classList.remove("show")},2200)}
async function LD(){try{var r=await fetch(API+"/students");var d=await r.json();if(Array.isArray(d))D.s=d}catch(e){}
try{var r=await fetch(API+"/courses");var d=await r.json();if(Array.isArray(d))D.c=d}catch(e){}
try{var r=await fetch(API+"/checkins");var d=await r.json();if(Array.isArray(d))D.k=d}catch(e){}
try{var r=await fetch(API+"/pauses");var d=await r.json();if(Array.isArray(d))D.p=d}catch(e){}}
function CM(){document.getElementById("modalOverlay").style.display="none";cb=null}
function OM(t,b,ok){document.getElementById("modalOverlay").style.display="flex";document.getElementById("modalContent").innerHTML="<h3>"+t+"</h3>"+b+'<div class="modal-actions"><button class="btn btn-outline" id="btnCancel">??</button><button class="btn btn-primary" id="btnOk">??</button></div>';if(ok)cb=ok}
function ST(n){T=n;var ns=document.querySelectorAll(".nav-item");for(var i=0;i<ns.length;i++)ns[i].classList.toggle("active",i===n);var titles=["?? ???","?? ????","?? ????","? ????","?? ????"];document.getElementById("pageTitle").textContent=titles[n];R()}
function R(){if(T===0)R0();else if(T===1)R1();else if(T===2)R2();else if(T===3)R3();else R4()}
function R0(){var m=document.getElementById("mainContent");var ac=D.c.filter(function(c){return c.status==="active"});var mc=ac.filter(function(c){return c.type==="monthly"}).length;var sc=ac.filter(function(c){return c.type==="session"}).length;var rev=D.c.reduce(function(t,c){return t+(c.price||0)},0);var td=(new Date()).toISOString().slice(0,10);var tdy=D.k.filter(function(k){return(k.date||k.checkinDate)===td}).length;var ps=D.p.filter(function(p){return p.status==="active"}).length;
m.innerHTML='<div class="stats-row"><div class="stat-card"><div class="stat-icon s1">??</div><div><div class="stat-val">'+D.s.length+'</div><div class="stat-lbl">????</div></div></div><div class="stat-card"><div class="stat-icon s2">??</div><div><div class="stat-val">?'+rev+'</div><div class="stat-lbl">???</div></div></div><div class="stat-card"><div class="stat-icon s3">??</div><div><div class="stat-val">'+mc+'/'+sc+'</div><div class="stat-lbl">??/??</div></div></div><div class="stat-card"><div class="stat-icon s4">?</div><div><div class="stat-val">'+tdy+'</div><div class="stat-lbl">????</div></div></div><div class="stat-card"><div class="stat-icon s5">??</div><div><div class="stat-val">'+ps+'</div><div class="stat-lbl">???</div></div></div>';
var h='<div class="card"><div class="card-header"><h2>?? ????</h2><div class="sub">'+D.s.length+' ?</div></div>';if(D.s.length===0)h+='<div class="empty"><div class="icon">??</div><p>????</p></div>';else{h+='<table><tr><th>??</th><th>???</th><th>???</th></tr>';D.s.forEach(function(s){var n=D.c.filter(function(c){return c.studentId===s.id}).length;h+='<tr><td><b>'+E(s.name)+'</b></td><td><a class="phone-link" href="tel:'+E(s.phone)+'">'+E(s.phone)+'</a></td><td>'+n+'</td></tr>'});h+='</table>'}h+='</div>';
var rc=D.k.slice().sort(function(a,b){return(b.createTime||b.date||"").localeCompare(a.createTime||a.date||"")}).slice(0,8);h+='<div class="card"><div class="card-header"><h2>?? ????</h2></div>';if(rc.length===0)h+='<div class="empty"><p>??????</p></div>';else{h+='<table><tr><th>??</th><th>??</th><th>??</th></tr>';rc.forEach(function(k){var s=GS(k.studentId);var isS=k.type==="session"||k.courseType==="session";h+='<tr><td><b>'+E(s.name)+'</b></td><td>'+F(k.date||k.checkinDate)+'</td><td><span class="tag '+(isS?"tag-session":"tag-monthly")+'">'+(isS?"??":"??")+'</span></td></tr>'});h+='</table>'}h+='</div>';m.innerHTML+=h}
function R1(){var m=document.getElementById("mainContent");var h='<div class="card"><div class="card-header"><h2>?? ????</h2><div class="search-box"><input placeholder="?? ????/??..." id="searchStudent"><button class="btn btn-primary btn-sm" id="btnAddStudent">+ ????</button></div></div>';if(D.s.length===0)h+='<div class="empty"><div class="icon">??</div><p>?????????????</p></div>';else{h+='<table><tr><th>??</th><th>???</th><th>??</th><th>??</th><th>??</th></tr>';D.s.forEach(function(s){var n=D.c.filter(function(c){return c.studentId===s.id}).length;h+='<tr><td><b>'+E(s.name)+'</b></td><td>'+E(s.phone)+'</td><td>'+E(s.note||"-")+'</td><td>'+n+'</td><td><button class="btn btn-outline btn-sm" data-edit-student="'+s.id+'">??</button> <button class="btn btn-danger btn-sm" data-del-student="'+s.id+'">??</button></td></tr>'});h+='</table>'}h+='</div>';m.innerHTML=h}
function R2(){var m=document.getElementById("mainContent");var h='<div class="card"><div class="card-header"><h2>?? ????</h2><button class="btn btn-primary btn-sm" id="btnAddCourse">+ ????</button></div>';if(D.c.length===0)h+='<div class="empty"><div class="icon">??</div><p>????</p></div>';else{h+='<table><tr><th>??</th><th>??</th><th>??</th><th>??</th><th>??</th><th>??</th></tr>';D.c.forEach(function(c){var s=GS(c.studentId);var isM=c.type==="monthly";var statusTag=c.status==="active"?"tag-active":c.status==="paused"?"tag-paused":"tag-expired";var statusLabel=c.status==="active"?"???":c.status==="paused"?"???":"???";h+='<tr><td><b>'+E(s.name)+'</b></td><td><span class="tag '+(isM?"tag-monthly":"tag-session")+'">'+(isM?"??":"??")+'</span></td><td><span class="tag '+statusTag+'">'+statusLabel+'</span></td><td>?'+(c.price||0)+'</td><td>'+(isM?(c.totalDays||30)+"?":(c.rem!==undefined?c.rem:c.total||10)+"/"+(c.total||10)+"?")+'</td><td><button class="btn btn-outline btn-sm" data-edit-course="'+c.id+'">??</button> <button class="btn btn-danger btn-sm" data-del-course="'+c.id+'">??</button></td></tr>'});h+='</table>'}h+='</div>';m.innerHTML=h}
function R3(){var m=document.getElementById("mainContent");var h='<div class="card"><div class="card-header"><h2>? ????</h2><div class="sub">? '+D.k.length+' ?</div></div>';if(D.k.length===0)h+='<div class="empty"><div class="icon">?</div><p>??????<br><small>??????????????</small></p></div>';else{var sorted=D.k.slice().sort(function(a,b){return(b.createTime||b.date||"").localeCompare(a.createTime||a.date||"")});h+='<table><tr><th>??</th><th>??</th><th>??</th><th>??</th><th>??</th></tr>';sorted.forEach(function(k){var s=GS(k.studentId);var isS=k.type==="session"||k.courseType==="session";h+='<tr><td><b>'+E(s.name)+'</b></td><td>'+F(k.date||k.checkinDate)+'</td><td>'+(k.time||k.checkinTime||"-")+'</td><td><span class="tag '+(isS?"tag-session":"tag-monthly")+'">'+(isS?"??":"??")+'</span></td><td><button class="btn btn-danger btn-sm" data-undo-checkin="'+k.id+'">??</button></td></tr>'});h+='</table>'}h+='</div>';m.innerHTML=h}
function R4(){var m=document.getElementById("mainContent");var act=D.p.filter(function(p){return p.status==="active"});var hist=D.p.filter(function(p){return p.status!=="active"});var h='<div class="card"><div class="card-header"><h2>?? ??????</h2><div class="sub">'+act.length+' ?</div></div>';if(act.length===0)h+='<div class="empty"><p>????????</p></div>';else{h+='<table><tr><th>??</th><th>??</th><th>??</th><th>??</th><th>??</th></tr>';act.forEach(function(p){var s=GS(p.studentId);h+='<tr><td><b>'+E(s.name)+'</b></td><td>'+F(p.date||p.pauseDate)+'</td><td>'+(p.type==="monthly"?"??":"??")+'</td><td>'+E(p.reason||"-")+'</td><td><button class="btn btn-outline btn-sm" data-resume-pause="'+p.id+'">??</button></td></tr>'});h+='</table>'}h+='</div>';if(hist.length>0){h+='<div class="card"><div class="card-header"><h2>?? ????</h2></div><table><tr><th>??</th><th>??</th><th>??</th></tr>';hist.slice(0,20).forEach(function(p){var s=GS(p.studentId);h+='<tr><td><b>'+E(s.name)+'</b></td><td>'+F(p.date||p.pauseDate)+'</td><td>'+E(p.reason||"-")+'</td></tr>'});h+='</table></div>'}m.innerHTML=h}
async function addStudent(){OM("????",'<div class="form-group"><label>?? *</label><input id="sn" placeholder="?????"></div><div class="form-row"><div class="form-group"><label>??? *</label><input id="sp" placeholder="11????"></div><div class="form-group"><label>??</label><input id="st" placeholder="??"></div></div>',async function(){var n=document.getElementById("sn").value.trim(),p=document.getElementById("sp").value.trim();if(!n||!p){TX("?????????");return}var r=await fetch(API+"/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n,phone:p,note:document.getElementById("st").value.trim()})});if(r.ok){await LD();R();TX("????")}else{TX("????")}})}
async function editStudent(id){var s=D.s.find(function(x){return x.id===id});if(!s)return;OM("????",'<div class="form-group"><label>??</label><input id="sn" value="'+E(s.name)+'"></div><div class="form-group"><label>???</label><input id="sp" value="'+E(s.phone)+'"></div><div class="form-group"><label>??</label><input id="st" value="'+E(s.note||"")+'"></div>',async function(){var n=document.getElementById("sn").value.trim(),p=document.getElementById("sp").value.trim();if(!n||!p)return;var r=await fetch(API+"/students/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n,phone:p,note:document.getElementById("st").value.trim()})});if(r.ok){await LD();R();TX("????")}else{TX("????")}})}
async function delStudent(id){if(!confirm("????????"))return;var r=await fetch(API+"/students/"+id,{method:"DELETE"});if(r.ok){await LD();R();TX("???")}else{TX("????")}}
function addCourse(){var opts=D.s.map(function(s){return '<option value="'+s.id+'">'+E(s.name)+' ('+E(s.phone)+')</option>'}).join("");OM("????",'<div class="form-group"><label>??</label><select id="cs">'+opts+'</select></div><div class="form-row"><div class="form-group"><label>??</label><select id="ct"><option value="monthly">??</option><option value="session">??</option></select></div><div class="form-group"><label>?? ?</label><input id="cp" type="number" value="0"></div></div><div class="form-row"><div class="form-group"><label>????</label><input id="cdr" type="date" value="'+new Date().toISOString().slice(0,10)+'"></div><div id="cgm" class="form-group"><label>??</label><input id="cdy" type="number" value="30"></div><div id="cgs" class="form-group" style="display:none"><label>??</label><input id="csn" type="number" value="10"></div></div>',async function(){var type=document.getElementById("ct").value;var d={studentId:document.getElementById("cs").value,type:type,status:"active",price:Number(document.getElementById("cp").value)||0,startDate:document.getElementById("cdr").value};if(type==="monthly"){var days=Number(document.getElementById("cdy").value)||30;d.totalDays=days;var end=new Date(d.startDate);end.setDate(end.getDate()+days);d.endDate=end.toISOString().slice(0,10)}else{var total=Number(document.getElementById("csn").value)||10;d.total=total;d.rem=total}var r=await fetch(API+"/courses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});if(r.ok){await LD();R();TX("????")}else{TX("????")}});setTimeout(function(){var ctEl=document.getElementById("ct");if(ctEl)ctEl.addEventListener("change",function(){document.getElementById("cgm").style.display=ctEl.value==="monthly"?"":"none";document.getElementById("cgs").style.display=ctEl.value==="monthly"?"none":""})},50)}
function editCourse(id){var c=D.c.find(function(x){return x.id===id});if(!c)return;var opts=D.s.map(function(s){return '<option value="'+s.id+'"'+(s.id===c.studentId?" selected":"")+'>'+E(s.name)+' ('+E(s.phone)+')</option>'}).join("");OM("????",'<div class="form-group"><label>??</label><select id="cs">'+opts+'</select></div><div class="form-row"><div class="form-group"><label>??</label><select id="cst"><option value="active"'+(c.status==="active"?" selected":"")+'>???</option><option value="paused"'+(c.status==="paused"?" selected":"")+'>???</option><option value="expired"'+(c.status==="expired"?" selected":"")+'>???</option></select></div><div class="form-group"><label>?? ?</label><input id="cp" type="number" value="'+(c.price||0)+'"></div></div>',async function(){var r=await fetch(API+"/courses/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:document.getElementById("cs").value,status:document.getElementById("cst").value,price:Number(document.getElementById("cp").value)||0})});if(r.ok){await LD();R();TX("????")}else{TX("????")}})}
async function delCourse(id){if(!confirm("????????"))return;var r=await fetch(API+"/courses/"+id,{method:"DELETE"});if(r.ok){await LD();R();TX("???")}else{TX("????")}}
async function undoCheckin(id){if(!confirm("????????"))return;var k=D.k.find(function(x){return x.id===id});var r=await fetch(API+"/checkins/"+id,{method:"DELETE"});if(r.ok){if(k&&(k.type==="session"||k.courseType==="session")&&(k.courseId||k.cid)){var cid=k.courseId||k.cid;var c=D.c.find(function(x){return x.id===cid});if(c)await fetch(API+"/courses/"+c.id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({rem:(c.rem||0)+1})})}await LD();R();TX("???")}else{TX("????")}}
async function resumePause(id){if(!confirm("????????"))return;var p=D.p.find(function(x){return x.id===id});if(!p)return;var r=await fetch(API+"/pauses/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"done"})});if(r.ok){if(p.courseId||p.cid){var cid=p.courseId||p.cid;await fetch(API+"/courses/"+cid,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"active"})})}await LD();R();TX("???")}else{TX("????")}}
document.addEventListener("click",function(e){var el=e.target;if(el.id==="btnCancel"){CM();return}if(el.id==="btnOk"){if(cb)cb();CM();return}if(el.id==="modalOverlay"&&e.target===el){CM();return}if(el.id==="btnRefresh"||el.closest("#btnRefresh")){LD().then(R);TX("???");return}var nav=el.closest(".nav-item");if(nav){ST(Number(nav.dataset.tab));return}if(el.id==="btnAddStudent"||el.closest("#btnAddStudent")){addStudent();return}var sid=el.dataset.editStudent||(el.closest("[data-edit-student]")||{}).dataset.editStudent;if(sid){editStudent(sid);return}var sd=el.dataset.delStudent||(el.closest("[data-del-student]")||{}).dataset.delStudent;if(sd){delStudent(sd);return}if(el.id==="btnAddCourse"||el.closest("#btnAddCourse")){addCourse();return}var cid=el.dataset.editCourse||(el.closest("[data-edit-course]")||{}).dataset.editCourse;if(cid){editCourse(cid);return}var cd=el.dataset.delCourse||(el.closest("[data-del-course]")||{}).dataset.delCourse;if(cd){delCourse(cd);return}var uid=el.dataset.undoCheckin||(el.closest("[data-undo-checkin]")||{}).dataset.undoCheckin;if(uid){undoCheckin(uid);return}var pid=el.dataset.resumePause||(el.closest("[data-resume-pause]")||{}).dataset.resumePause;if(pid){resumePause(pid);return}});
document.addEventListener("input",function(e){var el=e.target;if(el.id==="searchStudent"){var q=el.value.toLowerCase();document.querySelectorAll("table tr").forEach(function(r){if(r.querySelector("th"))return;var t=r.textContent.toLowerCase();r.style.display=t.includes(q)?"":"none"})}});
LD().then(function(){R()});
})();
